library(shiny)
library(shinythemes)
library(tidyverse)
library(MASS)
library(readxl)
library(nnet)
library(Boruta)
library(rhandsontable)
library(shinydashboard)
library(class)
library(leaps)
library(randomForest)

#Read the data
Species_Data<-read_excel('Species-Data.xlsx',na='NA')

#Changing the datatypes
a<-suppressWarnings(data.frame(sapply(Species_Data[,1:8],function(x) as.factor(x))))
a<-cbind(a,Species_Data[,-c(1:8)])
original<-a
#Omit the NAs
a<-na.omit(a)  

fact<-a[,1:8]#factor variables
nfact<-a[,-c(1:8)]#other variables

#correlation
tmp <- cor(a[,-c(1:8)])
tmp[upper.tri(tmp)] <- 0
diag(tmp) <- 0  

#remove highly correlated variables
data.new <- nfact[,!apply(tmp,2,function(x) any(x > 0.9))]
a<-data.frame(fact,data.new)
rm(list=c('fact','nfact','data.new','tmp')) 
Species_Data<-a[,c(6,9:length(a))]#Final
original[names(Species_Data)]->original

load("Parameter.Rdata")
#species_boruta<-Boruta(Species ~ ., data=Species_Data, doTrace=0)
#regsubsets(Species~.,Species_Data[,-48],really.big = T,nvmax=11)->regsubexh
#added method = 'forward' / 'backward' / 'seq' for the other selection methods
#Ignoring the 48th column as it had more zeros and was coming as an important predictor

ui <- dashboardPage(
    dashboardHeader(title = 'BatCalls'),
    dashboardSidebar(
        sidebarMenu(
            menuItem('Introduction',tabName = 'dashintro'),
            menuItem('Techniques',tabName = 'dashtech'),
            menuItem('Predict Species',tabName = 'dashpred'),
            menuItem('Conclusion',tabName = 'dashconc')
        )
    ),
    dashboardBody(
        tabItems(
            tabItem(tabName = 'dashintro',htmlOutput('intro')),
            tabItem(tabName = 'dashtech',htmlOutput('tech')),
            tabItem(tabName = 'dashpred',
                    fluidRow(selectInput("Function",label = "Select the prediction method",choices = c('LDA','QDA','KNN','Random Forest')),
                             selectInput('parametermethod',label = 'Variable selection method: ',choices = c('Boruta','Regsubsets')),
                             uiOutput('hideregsub'),
                             sliderInput('par','Number of variables to be used: ', min=2,max=11,5),
                             uiOutput('hideknn'),
                             box(actionButton("runButton","Predict the Species"))
                    ),
                    textOutput('specieserror'),
                    tabsetPanel(
                        tabPanel("Input", rHandsontableOutput('speciesdata')),
                        tabPanel("Predicted", DT::dataTableOutput("speciespredicted"))
                    )),
            tabItem(tabName = 'dashconc',htmlOutput('conc'))
        )
    )
)

server <- function(input, output,session) {
    observe(
        if(input$Function == 'Random Forest'){
            showModal(modalDialog(paste('It may take upto a minute to run the function. Please edit the data once the table becomes opaque.')))   
        }
    )
    
    output$intro<-renderUI({HTML(paste('Prediction the species of bats based on the information recorded on the sounds generated by bats.',
                                       'Known issues in the shiny app:','A warning will be displayed when you change the variable selection method from Boruta to Regsubsets for the first time',sep = '<br>'))})

    output$tech<-renderUI({HTML('Classification Methods used:<br>LDA<br>QDA<br>KNN<br>Random Forest<br><br>Parameter Selection Methods Used:<br>Boruta<br>Regsubsets')})

    output$hideknn<-renderUI({
        if(input$Function=='KNN')
            sliderInput('knnk','Number of nearest neighbours to compare for KNN ', min=1,max=30,3)
    })
    
    output$hideregsub<-renderUI({
        if(input$parametermethod=='Regsubsets')
            selectInput('regsubmethod',label = 'Regsubsets variable searching method ',choices = c('Exhaustive','Forward Selection','Backward Selection','Sequential Replacement'),selected = 'Exhaustive')
    })
    
    imps <- attStats(species_boruta)
    imps2 = imps[imps$decision != 'Rejected', c('meanImp', 'decision')]
    
#    observe({x<-input$parametermethod
#    if(x=='Regsubsets')
#        updateSliderInput(session, "par",min=2,max=8,value=5)
#    if(x=='Boruta')
#        updateSliderInput(session, "par",min=2,max=11,value=5)
#    })
    
    values <- reactiveValues()
    
    regsubf<-reactive({
        if(input$regsubmethod=="Exhaustive")
            regsubexh
        else if(input$regsubmethod=='Forward Selection')
            regsubforw
        else if(input$regsubmethod=='Backward Selection')
            regsubbac
        else if(input$regsubmethod=='Sequential Replacement')
            regsubseq
    })
    
    Species_Data1<-reactive({
        if(input$parametermethod=='Boruta'){
            rownames(head(imps2[order(-imps2$meanImp), ],input$par))->importantpar}
        else if(input$parametermethod=='Regsubsets'){
            importantpar<-names(coef(regsubf(),input$par))[-1]  }
       # Species_Data[,c("Species",importantpar)]
        na.omit(original[,c("Species",importantpar)])
    })
    
    output$speciesdata <- renderRHandsontable({

        head(Species_Data1()[,-1],4)->displayspecies
        rownames(displayspecies)<-NULL #was getting errors if we added a new record
        rhandsontable(displayspecies)
    })
    
    ldafunctionspecies<-reactive({
        lda(Species~., data = Species_Data1())
    })
    
    qdafunctionspecies<-reactive({
        qda(Species~., data = Species_Data1())
    })
    
    rfspecies<-reactive({
        randomForest(Species~.,data = Species_Data1())
    })
    
    observeEvent(input$runButton, {
        values$data <-  hot_to_r(input$speciesdata)
        if(input$Function == 'LDA'){
            values$data<-cbind(predict(ldafunctionspecies(),values$data)$class,values$data)
        }else if(input$Function == 'QDA'){
            values$data<-cbind(predict(qdafunctionspecies(),values$data)$class,values$data)
        }else if(input$Function == 'Random Forest'){
            values$data<-cbind(predict(rfspecies(),newdata=values$data),values$data)
        }
        else if(input$Function == 'KNN'){
            knntrain<-scale(Species_Data1()[,-1])
            means<-attr(knntrain,'scaled:center')
            sd<-attr(knntrain,'scaled:scale')
            knntest<-scale(values$data,center=means,scale = sd)
            knnresult<-knn(knntrain,knntest,Species_Data1()[,1],k = input$knnk)
            values$data<-cbind(knnresult,values$data)
        }
        names(values$data)[1]<-'Species'
    })
    
    output$speciespredicted <- DT::renderDataTable({
        values$data
    })  
    
    output$specieserror<-renderText({
        if(input$Function == 'LDA'){
            mean(predict(ldafunctionspecies())$class==Species_Data1()$Species)->errorspecies
            c('The model is ',round(errorspecies*100,2),'% accurate on the training data')}
        else if(input$Function == 'QDA'){
            mean(predict(qdafunctionspecies())$class==Species_Data1()$Species)->errorspecies
            c('The model is ',round(errorspecies*100,2),'% accurate on the training data')}
        else if(input$Function == 'Random Forest'){
            mean(predict(rfspecies())==Species_Data1()$Species)->errorspecies
            c('The model is ',round(errorspecies*100,2),'% accurate on the training data')}
        else if(input$Function == 'KNN')
            'You can edit the parameter k which has to be used in KNN'
    })
    
    output$conc <- renderUI({HTML(paste('Random Forest performs better',sep = '<br>'))})
    
}

# Run the application 
shinyApp(ui = ui, server = server)
